#pragma once //auto-generated by FMStudio
#include "fmsong.h"

static inline const FMSong fmSuper_Mario_Theme =
{
  .name="Super Mario Theme",
  .tempo=180,
  .instruments=
  {
    {
      .name="Piano",
      .algorithm=3, .volume=80, .feedback=50, .glide=0, .attack=0, .decay=75, .sustain=100, .release=60,
      .lfo={.speed=0, .attack=0, .pmd=0},
      .op=
      {
        {.level=71, .pitch={.fixed=false, .coarse=1, .fine=0}, .detune=50, .attack=0, .decay=70, .sustain=0, .loop=false}, 
        {.level=23, .pitch={.fixed=false, .coarse=1, .fine=0}, .detune=57, .attack=0, .decay=70, .sustain=0, .loop=false}, 
        {.level=20, .pitch={.fixed=false, .coarse=5, .fine=0}, .detune=51, .attack=0, .decay=70, .sustain=0, .loop=false}, 
        {.level=40, .pitch={.fixed=false, .coarse=1, .fine=0}, .detune=50, .attack=0, .decay=50, .sustain=0, .loop=false}
      }
    }
  },
  .patterns=
  {
    {
      .name="Intro (Treble)",
      .notes=
      {
        {76, 15, 127},
        {76, 15, 127},
        {0, 15, 127},
        {76, 15, 127},
        {0, 15, 127},
        {72, 15, 127},
        {76, 31, 127},
        {79, 31, 127},
        {0, 31, 127},
        {67, 31, 127},
        {0, 31, 127},
        {0, 0, 0}
      }
    },
    {
      .name="Intro (Bass)",
      .notes=
      {
        {50, 15, 127},
        {50, 15, 127},
        {0, 15, 127},
        {50, 15, 127},
        {0, 15, 127},
        {50, 15, 127},
        {50, 31, 127},
        {55, 31, 127},
        {0, 31, 127},
        {43, 31, 127},
        {0, 31, 127},
        {0, 0, 0}
      }
    }
  },
  .sections=
  {
    {{0, 0}},
    {{1, 0}},
    {},
    {}
  }
};
